"""Tracked Potrace parity limits for the black-box harness."""

PARITY_LIMITS = {
    "square": {
        "mask_ae_pixels": 0,
        "icon_command_count": 5,
        "icon_svg_point_count": 4,
        "icon_d_bytes": 25,
    },
    "circle": {
        "mask_ae_pixels": 0,
        "icon_command_count": 7,
        "icon_svg_point_count": 16,
        "icon_d_bytes": 125,
    },
    "two_circles": {
        "mask_ae_pixels": 0,
        "icon_command_count": 10,
        "icon_svg_point_count": 20,
        "icon_d_bytes": 163,
    },
    "ring": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 40,
        "icon_d_bytes": 297,
    },
    "triangle": {
        "mask_ae_pixels": 0,
        "icon_command_count": 8,
        "icon_svg_point_count": 8,
        "icon_d_bytes": 66,
    },
    "roundbar": {
        "mask_ae_pixels": 0,
        "icon_command_count": 8,
        "icon_svg_point_count": 19,
        "icon_d_bytes": 143,
    },
    "double_pill": {
        "mask_ae_pixels": 0,
        "icon_command_count": 22,
        "icon_svg_point_count": 38,
        "icon_d_bytes": 259,
    },
    "plus_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 22,
        "icon_svg_point_count": 46,
        "icon_d_bytes": 303,
    },
    "l_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 15,
        "icon_svg_point_count": 38,
        "icon_d_bytes": 240,
    },
    "l_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 34,
        "icon_d_bytes": 225,
    },
    "l_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 32,
        "icon_d_bytes": 218,
    },
    "l_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 32,
        "icon_d_bytes": 217,
    },
    "l_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 13,
        "icon_svg_point_count": 31,
        "icon_d_bytes": 206,
    },
    "l_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 34,
        "icon_d_bytes": 226,
    },
    "t_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 37,
        "icon_d_bytes": 250,
    },
    "t_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 37,
        "icon_d_bytes": 250,
    },
    "t_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 40,
        "icon_d_bytes": 250,
    },
    "t_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 37,
        "icon_d_bytes": 251,
    },
    "t_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 40,
        "icon_d_bytes": 250,
    },
    "t_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 38,
        "icon_d_bytes": 257,
    },
    "h_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 51,
        "icon_d_bytes": 342,
    },
    "h_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 51,
        "icon_d_bytes": 342,
    },
    "h_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 51,
        "icon_d_bytes": 342,
    },
    "h_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 50,
        "icon_d_bytes": 328,
    },
    "h_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 51,
        "icon_d_bytes": 342,
    },
    "h_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 23,
        "icon_svg_point_count": 50,
        "icon_d_bytes": 328,
    },
    "hooked_l": {
        "mask_ae_pixels": 0,
        "icon_command_count": 18,
        "icon_svg_point_count": 45,
        "icon_d_bytes": 283,
    },
    "hooked_l_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 41,
        "icon_d_bytes": 262,
    },
    "hooked_l_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 40,
        "icon_d_bytes": 261,
    },
    "hooked_l_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 40,
        "icon_d_bytes": 261,
    },
    "hooked_l_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 16,
        "icon_svg_point_count": 38,
        "icon_d_bytes": 248,
    },
    "hooked_l_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 17,
        "icon_svg_point_count": 41,
        "icon_d_bytes": 261,
    },
    "diagonal_bar": {
        "mask_ae_pixels": 0,
        "icon_command_count": 10,
        "icon_svg_point_count": 25,
        "icon_d_bytes": 179,
    },
    "angled_v": {
        "mask_ae_pixels": 0,
        "icon_command_count": 12,
        "icon_svg_point_count": 30,
        "icon_d_bytes": 224,
    },
    "angled_v_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 12,
        "icon_svg_point_count": 30,
        "icon_d_bytes": 224,
    },
    "angled_v_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 35,
        "icon_d_bytes": 261,
    },
    "angled_v_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 12,
        "icon_svg_point_count": 30,
        "icon_d_bytes": 227,
    },
    "angled_v_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 14,
        "icon_svg_point_count": 35,
        "icon_d_bytes": 261,
    },
    "angled_v_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 12,
        "icon_svg_point_count": 30,
        "icon_d_bytes": 228,
    },
    "rounded_rect_r18": {
        "mask_ae_pixels": 0,
        "icon_command_count": 13,
        "icon_svg_point_count": 33,
        "icon_d_bytes": 215,
    },
    "rounded_rect_r32": {
        "mask_ae_pixels": 0,
        "icon_command_count": 18,
        "icon_svg_point_count": 29,
        "icon_d_bytes": 198,
    },
    "u_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 27,
        "icon_svg_point_count": 39,
        "icon_d_bytes": 248,
    },
    "c_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 21,
        "icon_svg_point_count": 51,
        "icon_d_bytes": 354,
    },
    "f_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 41,
        "icon_svg_point_count": 57,
        "icon_d_bytes": 364,
    },
    "e_shape": {
        "mask_ae_pixels": 0,
        "icon_command_count": 26,
        "icon_svg_point_count": 57,
        "icon_d_bytes": 368,
    },
    "e_mx": {
        "mask_ae_pixels": 0,
        "icon_command_count": 27,
        "icon_svg_point_count": 60,
        "icon_d_bytes": 381,
    },
    "e_my": {
        "mask_ae_pixels": 0,
        "icon_command_count": 26,
        "icon_svg_point_count": 57,
        "icon_d_bytes": 368,
    },
    "e_r90": {
        "mask_ae_pixels": 0,
        "icon_command_count": 26,
        "icon_svg_point_count": 57,
        "icon_d_bytes": 361,
    },
    "e_r180": {
        "mask_ae_pixels": 0,
        "icon_command_count": 27,
        "icon_svg_point_count": 60,
        "icon_d_bytes": 381,
    },
    "e_r270": {
        "mask_ae_pixels": 0,
        "icon_command_count": 27,
        "icon_svg_point_count": 60,
        "icon_d_bytes": 386,
    },
}
